
#V1 <- seq(as.Date("2022-03-02"), as.Date("2022-03-04"), by="days")

#V6 <- strftime(V1, format = "%B%e,%Y")


D <- as.character(Sys.Date())
M <- strftime(D, format ="%B")
Full.d <- strftime(D, format = "%B%e, %Y")
extention <- strftime(D,format="%B-%Y")
link <- strftime(D,format="%Y%m%d")
picturefrom <- paste0("C:/Users/jason/Documents/birchwood/static/botticelli.jpg")
pictureto <- paste0("C:/Users/jason/Documents/birchwood/content/blog/",D,"/sidebar-featured.jpg")

dir.create(paste0("C:/Users/jason/Documents/birchwood/content/blog/",D))
dir.create(paste0("C:/Users/jason/Documents/birchwood/content/blog/",D,"/charts"))
dir.create(paste0("C:/Users/jason/Documents/birchwood/content/blog/",D,"/news"))
file.copy(picturefrom,pictureto)

top.file <- paste0("C:/Users/jason/Documents/birchwood/content/blog/",D,"/_index.md")

sink(top.file)
cat("---")
cat("\n")
cat("author: 1602")
cat("\n")
cat("cascade:")
cat("\n")
cat("author: 1602")
cat("\n")
cat("categories:")
cat("\n")
cat(paste("-", M))
cat("\n")
cat("layout: single-series")
cat("\n")
cat(paste("series:", Full.d))
cat("\n")
cat("show_author_byline: true")
cat("\n")
cat("show_post_date: true")
cat("\n")
cat("sidebar:")
cat("\n")
cat("show_sidebar_adunit: false")
cat("\n")
cat("text_contents_label: On this page")
cat("\n")
cat("text_link_label: Daily")
cat("\n")
cat(paste0("text_link_url: /markets/02-nasdaq/",extention))
cat("\n")
cat("text_series_label: In this series")
cat("\n")
cat("tags:")
cat("")
cat("\n")
cat("description: ")
cat("\n")
cat("layout: list-sidebar")
cat("\n")
cat("show_author_byline: true")
cat("\n")
cat("show_post_date: true")
cat("\n")
cat("show_post_thumbnail: false")
cat("\n")
cat("sidebar:")
cat("\n")
cat("author:")
cat("\n")
cat("description: ")
cat("show_sidebar_adunit: false")
cat("\n")
cat("text_link_label: Markets")
cat("\n")
cat("text_link_url: /markets/")
cat("\n")
cat(paste("title:", Full.d))
cat("\n")
cat("title:")
cat("\n")
cat("---")
sink()




  
  news.file<- paste0("C:/Users/jason/Documents/birchwood/content/blog/",D,"/news/index.md")
  sink(news.file)
  cat("---")
  cat("\n")
  cat("title: 'news'")
  cat("\n")
  cat(paste("date:", D))
  cat("\n")
  cat("draft: false")
  cat("\n")
  cat("excerpt:" )
  cat("\n")
  cat("subtitle: ")
  cat("\n")
  cat(paste("Title:", Full.d))
  cat("\n")
  cat("weight:") 
  cat("\n")
  cat("---")
  cat("\n")
  cat("\n")
  cat("---")
  cat("\n")
  cat(paste0("![](",link,"_0000xx.png)"))
  cat("\n")
  cat("---")
  cat("\n")
  cat(paste0("![](",link,"_0000xx.png)"))
  cat("\n")
  sink() 

  charts.file <- paste0("C:/Users/jason/Documents/birchwood/content/blog/",D,"/charts/index.md")
  sink(charts.file)
  cat("---")
  cat("\n")
  cat("title: 'charts'")
  cat("\n")
  cat(paste("date:", D))
  cat("\n")
  cat("draft: false")
  cat("\n")
  cat("excerpt:" )
  cat("\n")
  cat("subtitle: ")
  cat("\n")
  cat(paste0("Title:", Full.d))
  cat("\n")
  cat("weight:") 
  cat("\n")
  cat("---")
  cat("\n")
  cat("\n")
  cat("---")
  cat("\n")
  cat("{< panelset class='charts' >}}")
  cat("\n")
  cat("{< panel name='Nasdaq' >}}")
  cat("\n")
  cat(paste0("![](",link,"_0000xx.png)"))
  cat("\n")
  cat("{< /panel >}}")
  cat("\n")
  cat("{< panel name='S&P'>}}")
  cat("\n")
  cat(paste0("![](",link,"_0000xx.png)"))
  cat("\n")
  cat("{< /panel >}}")
  cat("\n")
  cat("{< /panelset >}}")
  sink()
